apiVersion: v1
kind: Service
metadata:
  name: instagram-api
  namespace: production-services
spec:
  selector:
    app: instagram-api
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  type: ClusterIP